name: task1_invites
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.2.1

